# 数据库配置
# 支持 mysql 和 sqlite 两种数据库类型

# 数据库类型：mysql 或 sqlite
type: sqlite

# MySQL 配置
mysql:
  host: localhost
  port: 3306
  database: onebot
  user: root
  password: ""
  useSSL: false

# SQLite 配置
sqlite:
  file: data/database.db

# 表前缀
tablePrefix: onebot_